# Generated by Django 4.2.9 on 2024-01-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
