# Generated by Django 5.0.1 on 2024-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(default='', upload_to='mp3_files/'),
            preserve_default=False,
        ),
    ]
