# Generated by Django 5.0.1 on 2024-01-19 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mood',
            name='title',
            field=models.CharField(choices=[('HAPPY', 'Happy'), ('CALM', 'Calm'), ('SAD', 'Sad'), ('BORED', 'Bored'), ('ANXIOUS', 'Anxious'), ('ANGRY', 'Angry')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
