# Generated by Django 5.0.1 on 2024-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mood_content_mood_date_alter_mood_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('HAPPY', 'Happy'), ('CALM', 'Calm'), ('SAD', 'Sad'), ('BORED', 'Bored'), ('ANXIOUS', 'Anxious'), ('ANGRY', 'Angry')], max_length=7),
        ),
    ]
