# Generated by Django 5.0.1 on 2024-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='title',
            field=models.CharField(choices=[('HAPPY', 'Happy'), ('CALM', 'Calm'), ('SAD', 'Sad'), ('BORED', 'Bored'), ('ANXIOUS', 'Anxious'), ('ANGRY', 'Angry')], max_length=7, verbose_name='How are you feeling?'),
        ),
    ]
