# Generated by Django 5.0.1 on 2024-01-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_mood_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mood')),
            ],
        ),
    ]
