# Generated by Django 5.0.1 on 2024-01-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_customuser_avatar'),
        ('main_app', '0008_moodphoto'),
    ]

    operations = [
    ]
