# Generated by Django 5.0.1 on 2024-01-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_0008_customuser_avatar_0008_moodphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodphoto',
            name='url',
            field=models.URLField(),
        ),
    ]
