# Generated by Django 5.0.1 on 2024-01-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_customuser_avatar'),
        ('main_app', '0010_alter_moodphoto_url'),
    ]

    operations = [
    ]
