# Generated by Django 4.2.9 on 2024-01-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_customuser_avatar'),
        ('main_app', '0010_alter_moodphoto_url'),
    ]

    operations = [
    ]
