# Generated by Django 5.0.1 on 2024-01-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20240123_1431'),
        ('main_app', '0011_merge_20240123_1435'),
        ('main_app', '0011_merge_20240123_1440'),
    ]

    operations = [
    ]
